version: '3.7'

services:

  #  goreit-service:
  #    image: goreit/goreit
  #    volumes:
  #      - goreit-service-data:/root
  #    ports:
  #      - 8080:8080
  #    depends_on:
  #      - 'mongodb'
  #      - 'postgres'
  #    environment:
  #      SPRING_PROFILES_ACTIVE: "dev"

  mongodb:
    image: mongo:4.0.0
    volumes:
      - goreit-mongodb-data:/data/db
    ports:
      - 27017:27017
    command: mongod
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2000M
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - goreit


#  postgres:
#    image: postgres
#    volumes:
#      - goreit-postgres-data:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=camunda
#      - PGDATA=postgres
#    networks:
#      - goreit

networks:
  goreit:

volumes:
  goreit-rabbitmq-data:
  goreit-service-data:
  goreit-mongodb-data:
  goreit-solr-data:
  goreit-postgres-data:



